package basedef

var (
	PRICE_PRECISION = int64(100000000)
	FEE_PRECISION   = int64(100000000)
)

var (
	MARKET_COINMARKETCAP = "coinmarketcap"
	MARKET_BINANCE       = "binance"
	MARKET_HUOBI         = "huobi"
	MARKET_SELF          = "self"
)

const (
	STATE_FINISHED = iota
	STATE_PENDDING
	STATE_SOURCE_DONE
	STATE_SOURCE_CONFIRMED
	STATE_POLY_CONFIRMED
	STATE_DESTINATION_DONE
)

var (
	POLY_CROSSCHAIN_ID     = uint64(0)
	BTC_CROSSCHAIN_ID      = uint64(1)
	ETHEREUM_CROSSCHAIN_ID = uint64(2)
	ONT_CROSSCHAIN_ID      = uint64(3)
	NEO_CROSSCHAIN_ID      = uint64(4)
	SWITCHEO_CROSSCHAIN_ID = uint64(5)
	BSC_CROSSCHAIN_ID      = uint64(6)
	HECO_CROSSCHAIN_ID     = uint64(7)
	O3_CROSSCHAIN_ID       = uint64(10)
)

const (
	SERVER_POLY_BRIDGE = "polybridge"
	SERVER_POLY_SWAP   = "polyswap"
	SERVER_EXPLORER    = "explorer"
	SERVER_ADDRESS     = "address"
	SERVER_STAKE       = "stake"
)

const (
	ADDRESS_LENGTH = 64
)

const (
	SWAP_SWAP = iota
	SWAP_ADDLIQUIDITY
	SWAP_REMOVELIQUIDITY
	SWAP_ROLLBACK
)
